fun main() {
    println("student Enrollment No.: ")
    var a = readLine()
    println("student Name : ")
    var b = readLine()
    println("student Branch : ")
    var c = readLine()
    println("student Class : ")
    var d = readLine()
    println("student Batch : ")
    var e = readLine()
    println("student College Name : ")
    var f = readLine()
    println("student University Name : ")
    var g = readLine()
    println("student Age : ")
    var h = readLine()

    println("*********************************")

    println("Student's Data : ")
    println("Enrollment No. : "+a)
    println("Name : "+b)
    println("Age : "+h)
    println("Branch : "+c)
    println("Class : "+d)
    println("Batch : "+e)
    println("College Name : "+f)
    println("University Name : "+g)
}